const String LoginViewRoute = "LoginView";
const String SignUpViewRoute = "SignUpView";
const String HomeViewRoute = "HomeView";
const String MainViewRoute = "MainView";
const String EventViewRoute = "EventView";
const String ProfileViewRoute = "ProfileView";
const String EventDetailViewRoute = "EventDetailView";
const String EditEventViewRoute = "EditEventView";
const String ProfileEditViewRoute = "ProfileEditView";
// Generate the views here