// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoRr7yUclexPVk3ebBJthEgTKi9qXMK8s',
    appId: '1:742983309567:web:0bfe5358688f43f600d4ca',
    messagingSenderId: '742983309567',
    projectId: 'fluttertutorial-6179c',
    authDomain: 'fluttertutorial-6179c.firebaseapp.com',
    storageBucket: 'fluttertutorial-6179c.appspot.com',
    measurementId: 'G-NEHWNZKYDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDCdZW3_YxNPnTsoS6mP64kzSXBiAIwCY',
    appId: '1:742983309567:android:9ee027849de85f4900d4ca',
    messagingSenderId: '742983309567',
    projectId: 'fluttertutorial-6179c',
    storageBucket: 'fluttertutorial-6179c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCARIJ94PLXT7NTLgF1RntrIEwuiiqTy8E',
    appId: '1:742983309567:ios:dc80741c0adac6fc00d4ca',
    messagingSenderId: '742983309567',
    projectId: 'fluttertutorial-6179c',
    storageBucket: 'fluttertutorial-6179c.appspot.com',
    iosClientId: '742983309567-0dshg30b5tegggp7o9gr8cc9bcbokfm7.apps.googleusercontent.com',
    iosBundleId: 'com.sooyoung.flutterauth',
  );
}
